-- MANUAL REVIEW REQUIRED: verify titles, difficulty, and topic mapping before production use.
insert into public.coding_problems (leetcode_slug, title, difficulty, topic_id)
select problems.slug, problems.title, problems.difficulty, topics.id
from (values
 ('two-sum','Two Sum','Easy','Arrays & Strings'), ('best-time-to-buy-and-sell-stock','Best Time to Buy and Sell Stock','Easy','Arrays & Strings'), ('contains-duplicate','Contains Duplicate','Easy','Arrays & Strings'), ('product-of-array-except-self','Product of Array Except Self','Medium','Arrays & Strings'), ('maximum-subarray','Maximum Subarray','Medium','Arrays & Strings'), ('3sum','3Sum','Medium','Arrays & Strings'), ('merge-intervals','Merge Intervals','Medium','Arrays & Strings'), ('rotate-array','Rotate Array','Medium','Arrays & Strings'),
 ('valid-anagram','Valid Anagram','Easy','Hashing'), ('group-anagrams','Group Anagrams','Medium','Hashing'), ('two-sum-ii-input-array-is-sorted','Two Sum II','Medium','Hashing'), ('longest-consecutive-sequence','Longest Consecutive Sequence','Medium','Hashing'), ('top-k-frequent-elements','Top K Frequent Elements','Medium','Hashing'), ('design-hashmap','Design HashMap','Easy','Hashing'),
 ('valid-parentheses','Valid Parentheses','Easy','Trees'), ('binary-tree-inorder-traversal','Binary Tree Inorder Traversal','Easy','Trees'), ('maximum-depth-of-binary-tree','Maximum Depth of Binary Tree','Easy','Trees'), ('invert-binary-tree','Invert Binary Tree','Easy','Trees'), ('validate-binary-search-tree','Validate Binary Search Tree','Medium','Trees'), ('lowest-common-ancestor-of-a-binary-search-tree','Lowest Common Ancestor of a BST','Medium','Trees'), ('binary-tree-level-order-traversal','Binary Tree Level Order Traversal','Medium','Trees'), ('serialize-and-deserialize-binary-tree','Serialize and Deserialize Binary Tree','Hard','Trees'),
 ('number-of-islands','Number of Islands','Medium','Graphs'), ('clone-graph','Clone Graph','Medium','Graphs'), ('course-schedule','Course Schedule','Medium','Graphs'), ('pacific-atlantic-water-flow','Pacific Atlantic Water Flow','Medium','Graphs'), ('rotting-oranges','Rotting Oranges','Medium','Graphs'), ('word-ladder','Word Ladder','Hard','Graphs'), ('network-delay-time','Network Delay Time','Medium','Graphs'), ('graph-valid-tree','Graph Valid Tree','Medium','Graphs'),
 ('climbing-stairs','Climbing Stairs','Easy','Dynamic Programming'), ('house-robber','House Robber','Medium','Dynamic Programming'), ('coin-change','Coin Change','Medium','Dynamic Programming'), ('longest-increasing-subsequence','Longest Increasing Subsequence','Medium','Dynamic Programming'), ('word-break','Word Break','Medium','Dynamic Programming'), ('decode-ways','Decode Ways','Medium','Dynamic Programming'), ('unique-paths','Unique Paths','Medium','Dynamic Programming'), ('edit-distance','Edit Distance','Hard','Dynamic Programming')
) as problems(slug, title, difficulty, topic_name)
join public.topics on public.topics.name = problems.topic_name and public.topics.category = 'DSA'
on conflict (leetcode_slug) do nothing;
